export const QUERY_KEY = {
  USER: 'USER',
  USERS: 'USERS',
  POST: 'POST',
  POST_EDITOR: 'POST_EDITOR',
  POSTS_PUBLISHED: 'POST_PUBLISHED',
  POSTS_DRAFTS: 'POST_DRAFTS',
  POSTS_DELETED: 'POST_DELETED',
  TAGS: 'TAGS',
};
